M48
; DRILL file {KiCad 9.0.7} date 2026-09-11T23:59:54-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-11T23:59:54-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.900
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C1.200
%
G90
G05
T1
X183.96Y-116.0
X186.5Y-116.0
T2
X117.5Y-114.0
X117.5Y-116.54
T3
X140.34Y-93.0
X160.66Y-93.0
M30
